version: '3.7'

networks:
  all-in-one:
    driver: "${NETWORK_MODE}"
    attachable: true
    enable_ipv6: false

services:
  
  web:
    hostname: web
    build: ./
    entrypoint: ./docker-entrypoint.sh
    restart: on-failure
    stop_grace_period: 2s
    stop_signal: SIGTERM
    init: true
    networks:
      - all-in-one
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    ports:
      - "4000:4000/tcp"
    volumes:
      - "./docker-entrypoint.sh:/application/docker-entrypoint.sh:ro"
      - "./assets:/application/assets:ro"
      - "./config:/application/config:ro"
      - "./lib:/application/lib:ro"
      - "./lib/animina/accounts/resources/user.ex:/application/lib/animina/accounts/resources/user.ex:rw"
      - "./mix.exs:/application/mix.exs:ro"
      - "./mix.lock:/application/mix.lock:ro"
      - "./priv:/application/priv:ro"
      - "./priv/static/assets:/application/priv/static/assets:rw"  # note: read-write!
      - "./priv/repo/migrations:/application/priv/repo/migrations:rw"  # note: read-write!
      - "./priv/resource_snapshots/repo:/application/priv/resource_snapshots/repo:rw"  # note: read-write!
      - "./test:/application/test:ro"
      - "./.formatter.exs:/application/.formatter.exs:ro"
      - "./.credo.exs:/application/.credo.exs:ro"
      - "./.git:/application/.git:ro"  # just so we can compare changes made by "mix format", as an experiment
      - "./.gitignore:/application/.gitignore:ro"  # just so we can compare changes made by "mix format", as an experiment
    depends_on:
      db:
        condition: service_started
    environment:
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "postgres"
      DATABASE_HOST: "db"
      DATABASE_NAME: "animina_dev"
  
  db:
    hostname: db
    #image: postgres:16
    build: ./db-docker/
    restart: on-failure
    networks:
      - all-in-one
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 1
    ports:
      - "5432:5432/tcp"  # for external access
    #volumes:
    #  - "./db-docker/dumps/z-2024.sql:/docker-entrypoint-initdb.d/z-2024.sql"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      

# For Emacs:
# Local Variables:
# indent-tabs-mode:nil
# tab-width:2
# c-basic-offset:2
# End:
# For VIM:
# vim:set softtabstop=2 shiftwidth=2 tabstop=2 expandtab:

