# Name of your application. Used to uniquely configure containers.
service: animina

<% require "dotenv"; Dotenv.load(".env") %>

# Name of the container image.
image: <%= ENV["DEV_CONTAINER_IMAGE"] %>

# Deploy to these servers.
servers:
  web:
    hosts:
      - <%= ENV["DEV_SERVER_IP"] %>
    options:
      publish: <%= ENV["DEV_PORT"] %>:4000
    proxy: false

# Credentials for your image host.
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  # local: false
  arch: amd64
  # remote: <%= ENV["REMOTE_BUILDER_SSH_URL"] %>

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    PORT: 4000
    MIX_ENV: prod
  secret:
    - DATABASE_URL
    - SECRET_KEY_BASE
    - PHX_HOST
    - DISABLE_ML_FEATURES

ssh:
  user: root

# Use a persistent storage volume.
#
# volumes:
#   - "app_storage:/app/storage"

