# Name of your application. Used to uniquely configure containers.
service: animina-prod

<% require "dotenv"; Dotenv.load(".env") %>

# Name of the container image.
image: <%= ENV["PROD_CONTAINER_IMAGE"] %>

# Deploy to these servers.
servers:
  web:
    hosts:
      - <%= ENV["PROD_SERVER_IP"] %>
    options:
      publish: <%= ENV["PROD_PORT"] %>:4000
    proxy: false

# Credentials for your image host.
registry:
  server: ghcr.io
  username:
    - KAMAL_REGISTRY_USERNAME
  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    PORT: 4000
    MIX_ENV: prod
  secret:
    - SECRET_KEY_BASE
    - PHX_HOST
    - DISABLE_ML_FEATURES
    - DATABASE_URL

ssh:
  user: root

# Use a persistent storage volume.
#
volumes:
  - "<%= ENV["PROD_FILE_VOLUME_PATH"] %>:/uploads"

