name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0,15,30,45 * * * *' # every 15 minutes

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Sync Fork
      uses: TG908/fork-sync@v1
      with:
        head: main
        base: main
        upstream_repository: git@github.com:animina-dating/animina.git
        upstream_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
