name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0,15,30,45 * * * *' # every 15 minutes

jobs:
  check-upstream:
    runs-on: ubuntu-latest
    outputs:
      is-upstream: ${{ steps.check-repo.outputs.is-upstream }}
    steps:
    - name: Check if this is the upstream repository
      id: check-repo
      run: |
        if [ "${{ github.repository }}" = "animina-dating/animina" ]; then
          echo "::set-output name=is-upstream::true"
        else
          echo "::set-output name=is-upstream::false"
        fi

  sync:
    needs: check-upstream
    if: needs.check-upstream.outputs.is-upstream == 'false'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Sync Fork
      uses: TG908/fork-sync@v1
      with:
        head: main
        base: main
        upstream_repository: git@github.com:animina-dating/animina.git
        upstream_branch: main
        github_token: ${{ secrets.GITHUB_TOKEN }}
