name: Update Patch Version

on:
  schedule:
    - cron: '0 12 * * *'  # Dies bedeutet, dass das Skript jeden Tag um 12:00 Uhr mittags UTC ausgeführt wird
  workflow_dispatch:  # Optional, ermöglicht das manuelle Auslösen des Workflows

jobs:
  update-patch-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: '1.16.3'
        otp-version: '26.2.5'

    - name: Check for changes
      id: changes
      run: |
        git fetch origin
        git diff --exit-code origin/main || echo "Changes detected"

    - name: Update patch version
      if: steps.changes.outcome != 'success'
      run: |
        # Extrahiere die aktuelle Version
        current_version=$(grep 'version:' mix.exs | sed -E "s/.*version: \"([0-9]+\.[0-9]+\.[0-9]+)\".*/\1/")
        IFS='.' read -ra ADDR <<< "$current_version"
        patch=${ADDR[2]}
        new_patch=$((patch + 1))
        new_version="${ADDR[0]}.${ADDR[1]}.$new_patch"

        # Aktualisiere die mix.exs Datei
        sed -i "s/$current_version/$new_version/" mix.exs

        # Commit und Push der Änderungen
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add mix.exs
        git commit -m "Bump patch version to $new_version"
        git push origin main
