name: Update Patch Version

on:
  schedule:
    - cron: '0 12 * * *'  # This means the script will run every day at 12:00 PM UTC
  workflow_dispatch:  # Optional, allows manual triggering of the workflow

jobs:
  update-patch-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for changes
      id: changes
      run: |
        git fetch origin
        git diff --exit-code origin/main || echo "Changes detected"

    - name: Debug check changes
      run: |
        git diff origin/main
        git status

    - name: Update patch version
      if: steps.changes.outcome != 'success'
      run: |
        # Extract the current version
        current_version=$(grep 'version:' mix.exs | sed -E "s/.*version: \"([0-9]+\.[0-9]+\.[0-9]+)\".*/\1/")
        echo "Current version: $current_version"
        IFS='.' read -ra ADDR <<< "$current_version"
        patch=${ADDR[2]}
        new_patch=$((patch + 1))
        new_version="${ADDR[0]}.${ADDR[1]}.$new_patch"
        echo "New version: $new_version"

        # Update the mix.exs file
        sed -i "s/$current_version/$new_version/" mix.exs

        # Verify the update
        grep 'version:' mix.exs

        # Commit and push the changes
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add mix.exs
        git commit -m "Bump patch version to $new_version"
        git push origin main
